openapi: 3.0.0
info:
  version: 1.0.0
  title: MAJER OTANG API
  description: see api_link
paths:
  /members:
    get:
      description: GET all members
      tags: ['Members']
      operationId: 'getMemberList'
      summary: GET all member
      responses:
        '200':
          description: Success GET all members
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/GetMemberListResponse'

  /members/{memberId}:
    get:
      description: GET member by memberId
      tags: ['Members']
      operationId: 'getMemberDetail'
      summary: GET member by memberId
      parameters:
        - name: memberId
          in: path
          schema:
            type: string
          required: true
          description: Member Id
      responses:
        '200':
          description: Success GET member by memberId
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/GetMemberDetailResponse'
        '404':
          description: Member not found
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    GetMemberListResponse:
      type: object
      'required':
        - 'data'
        - 'status'
        - 'message'
      properties:
        data:
          type: array
          items:
            $ref: '#/components/Member'
        status:
          type: string
        message:
          type: string
    GetMemberDetailResponse:
      type: object
      'required':
        - 'data'
        - 'status'
        - 'message'
      properties:
        data:
          $ref: '#/components/Member'
        status:
          type: string
        message:
          type: string
    Member:
      type: object
      'required':
        - 'id'
        - 'name'
      properties:
        id:
          type: string
          x-go-custom-tag: bson:"_id"
        name:
          type: string
          x-go-custom-tag: bson:"name"
    ErrorResponse:
      type: object
      'required':
        - 'data'
        - 'status'
        - 'message'
      properties:
        data:
          type: null
        status:
          type: string
        message:
          type: string
